# definir el alcance de los hosts
- name: Deployment de un sitio estatico
  hosts: all
  become: yes
  pre_tasks:
    - name: Verificar si el OS es Ubuntu
      set_fact:
        is_ubuntu: "{{ ansible_distribution == 'Ubuntu' }}"
  vars:
    site_dir: /var/www/html/ansible_site
  tasks:
    - name: Actualizar el cache de paqutes.
      apt:
        update_cache: yes
      when: is_ubuntu
    - name: Instalar Apache2
      apt:
        name: apache2
        state: present
      when: is_ubuntu
    - name: Verificar que apache este corriendo
      service:
        name: apache2
        state: started
        enabled: yes
      when: is_ubuntu
    - name: crear directorio para el sitio
      file:
        path: /var/www/html/ansible_site
        state: directory
        owner: www-data
        group: www-data
      when: is_ubuntu
    - name: copiar index.html al directorio del sitio
      copy:
        src: files/index.html
        dest: "{{ site_dir }}"
        owner: www-data
        group: www-data
        mode: '0644'
      when: is_ubuntu
    - name: Configuracion del sitio apache
      template:
        src: templates/ansible_site.conf.j2
        dest: /etc/apache2/sites-available/ansible_site.conf
      notify:
        - Reload Apache
      when: is_ubuntu
    - name: Activa el nuevo sitio
      command: a2ensite ansible_site.conf
      notify:
        - Reload Apache
      when: is_ubuntu
    - name: Deshabilita el sitio default
      command: a2dissite 000-default.conf
      notify:
        - Reload Apache
      when: is_ubuntu
  handlers:
    - name: Reload Apache
      service:
        name: apache2
        state: reloaded
      when: is_ubuntu